- name: nginx_playbook
  hosts: targets_based_on_Docker
  vars:
    package_dict:
       - { name: "nginx", state: "absent" }
       - { name: "nodejs", state: "latest" }
       - { name: "postgresql", state: "present" }

  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes

    - name: Install packages based on dictionary values
      apt:
        name : "{{ item.name }}"
        state : "{{ item.state }}"
      loop : "{{ package_dict }}"
